#!/usr/bin/env node
/**
 * Generate badges.js from scraped badge data.
 * Reads badges-data.json and outputs the final badges.js source code.
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(__dirname, "badges-data.json"), "utf8"));
const OUTPUT = join(__dirname, "..", "src/data/badges.js");

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\s+badge$/i, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_");
}

function camelCase(str) {
  return str
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()))
    .join("");
}

// Build import statements and badge array
const imports = [];
const badgeEntries = [];

// Known categories based on the original badges.js data
// Badges that require booster packs (some or all familiars obtained via Cash Shop boosters)
const boosterRequired = new Set([
  "Shadow Badge", "Magical Badge", "Beach Badge", "Machine Badge",
  "Toy Badge", "Forest Badge", "Wings Badge", "Shrine Badge",
  "City Badge", "Mighty Badge", "Exorcism Badge", "Cursed Badge",
  "Dragon Badge", "Darkness Badge",
]);

const importSet = new Set(); // track globally unique import names

for (const badge of data) {
  const slug = slugify(badge.name);
  const badgeId = slug;
  const category = boosterRequired.has(badge.name) ? "booster-required" : "no-booster";

  // Generate import for each familiar icon, deduplicating within the badge
  const famImports = [];
  const seenInBadge = new Set();

  for (const fam of badge.familiars) {
    // Skip duplicate familiars within the same badge (wiki data errors)
    if (seenInBadge.has(fam.name)) continue;
    seenInBadge.add(fam.name);

    const filename = sanitizeFilename(fam.name) + "_Familiar.png";
    const uniqueImportName = `icon_${slug.replace(/-/g, "_")}_${sanitizeFilename(fam.name)}`;
    const importPath = `../assets/icons/${slug}/${filename}`;

    // Only add import if not already declared globally
    if (!importSet.has(uniqueImportName)) {
      imports.push(`import ${uniqueImportName} from "${importPath}";`);
      importSet.add(uniqueImportName);
    }
    famImports.push({ name: fam.name, importName: uniqueImportName });
  }

  // Build badge entry
  const familiarLines = famImports
    .map((f) => `      fam("${f.name}", ${f.importName})`)
    .join(",\n");

  badgeEntries.push(`  {
    id: "${badgeId}",
    name: "${badge.name}",
    category: "${category}",
    effects: "${badge.effects.replace(/"/g, '\\"')}",
    familiars: [
${familiarLines},
    ],
  }`);
}

const source = `/**
 * MapleStory Familiar Badge Data
 * Source: https://maplestory.fandom.com/wiki/Familiars
 *
 * Auto-generated by scripts/generate-badges.mjs
 * Total: ${data.length} badges, ${data.reduce((s, b) => s + b.familiars.length, 0)} familiars
 *
 * Categories:
 *   - 'no-booster'       → Does NOT require Booster Packs
 *   - 'booster-required'  → Requires Booster Packs (some or all familiars)
 */

// Bundled reference icons (auto-generated imports)
${imports.join("\n")}

let _uid = 0;
function fam(name, icon) {
  const f = { id: \`fam-\${++_uid}\`, name: \`\${name} Familiar\` };
  if (icon) f.icon = icon;
  return f;
}

export const badges = [
${badgeEntries.join(",\n")},
];

/** Total familiar count across all badges */
export const totalFamiliars = badges.reduce(
  (sum, b) => sum + b.familiars.length,
  0,
);

/** Maximum cumulative badge stat caps */
export const statCaps = {
  STR: "+2",
  DEX: "+2",
  INT: "+2",
  LUK: "+2",
  "All Stats (Flat)": "+2",
  "All Stats (%)": "+1%",
  "Max HP (Flat)": "+10",
  "Max HP (%)": "+2%",
  "Max MP": "+5",
  "Defense (Flat)": "+10",
  "Defense (%)": "+2%",
  "ATT (Flat)": "+2",
  "ATT (%)": "+3%",
  "MATT (Flat)": "+2",
  "MATT (%)": "+3%",
  Speed: "+2",
  Jump: "+2",
  Damage: "+3%",
  "Crit Rate": "+3%",
  IED: "+15%",
};
`;

writeFileSync(OUTPUT, source);
console.log(`✅ Generated ${OUTPUT}`);
console.log(`   ${data.length} badges, ${data.reduce((s, b) => s + b.familiars.length, 0)} familiars`);
console.log(`   ${imports.length} icon imports`);
